os: linux
dist: bionic

language:
    - cpp

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev
    - sudo apt-get install -y qt5-default qttools5-dev-tools
    - sudo apt install build-essential
    - sudo git clone https://github.com/tplgy/cppcodec.git && cd cppcodec && sudo cmake . -DBUILD_TESTING=OFF && sudo make install && cd ..
    #- pip install --user cpp-coveralls

#addons:
    #sonarcloud:
        #organization: "rakabidasta"
    #token: $SONAR_TOKEN

script:
    - qmake 
    - make
    - ./tests/tests
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
    email: false 
